const DefaultSettings = {
	slug         : '',
	types        : ['post'],
	function_name: 'your_prefix_register_taxonomy',
	text_domain  : 'your-textdomain',

	labels       : {
		name                      : '',
		singular_name             : '',
		menu_name                 : '',
		search_items              : '',
		popular_items             : '',
		all_items                 : '',
		parent_item               : '',
		parent_item_colon         : '',
		edit_item                 : '',
		view_item                 : '',
		update_item               : '',
		add_new_item              : '',
		new_item_name             : '',
		separate_items_with_commas: '',
		add_or_remove_items       : '',
		choose_from_most_used     : '',
		not_found                 : '',
		no_terms                  : '',
		filter_by_item            : '',
		items_list_navigation     : '',
		items_list                : '',
		most_used                 : '',
		back_to_items             : '',
	},
	description       : '',
	public            : true,
	publicly_queryable: true,
	hierarchical      : false,
	show_ui           : true,
	show_in_menu      : true,
	show_in_nav_menus : true,
	meta_box_cb       : 'post_tags_meta_box',
	show_in_rest      : true,
	rest_base         : '',
	show_tagcloud     : true,
	show_in_quick_edit: true,
	show_admin_column : false,
	rewrite           : {
		slug        : '',
		with_front  : false,
		hierarchical: false,
	},
	query_var         : true,
	sort              : false,
};

export default DefaultSettings;